# Generated by Django 3.2.8 on 2022-08-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.CharField(max_length=50, unique=True)),
                ('no_of_calls', models.PositiveIntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=100)),
                ('thumbnail_default', models.URLField()),
                ('channel_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at', '_id'],
            },
        ),
        migrations.CreateModel(
            name='Video_Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_videos', to='ytcron.keyword')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_keywords', to='ytcron.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['_id', 'published_at'], name='ytcron_vide__id_282367_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='video_keyword',
            unique_together={('keyword', 'video')},
        ),
    ]
