# Generated by Django 3.2.8 on 2022-08-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ytcron", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="valid",
            new_name="working",
        ),
    ]
